### ISSUE TITLE
Add config settings for overwriting projects

### ISSUE THREAD

**Issue by wine-ff2** [wine-ff2/tia-portal-automation-tool#7]
When a project exists, the script crashes when a project already exists. I recommend adding a new key for the config `overwrite` which removes the existing project and start a new one.

```json
{
    "version" : 18,
    "filename" : "Siemens.Engineering.dll",
    "dll": "C:/Program Files/Siemens/Automation/Portal V18/PublicAPI/V18/Siemens.Engineering.dll",
    "project" : {
            "name" : "JSONConfigExample3",
            "directory" : "C:/Users/Chi/Desktop/TIA/",
            "overwrite" : true
     }
...
}
```

**Comment by chickenness** [comment]
Better method is to just increment. It saves us from having to deal with directory deletion recursion #13

**Comment by wine-ff2** [comment]
Better method is to just increment. It saves us from having to deal with directory deletion recursion #13

**Comment by wine-ff2** [comment]
Reopening since this method is better.
